### ISSUE TITLE
Consider re-licensing to a more permissive license

### ISSUE THREAD

**Issue by nielsvd** [pryre/tinyspline_ros#1]
We would like to use this ROS package but have noticed that your contributions are licensed under GPL, instead of MIT like the tinyspline library itself. Would you consider changing this?

Note that most ROS packages are licensed under BSD 3-Clause, MIT, or Apache 2.0.

**Comment by pryre** [comment]
Good call, and I was probably far too late in checking this. Updated in [1ccc782](https://github.com/pryre/tinyspline_ros/commit/1ccc7828cf196b6d91e3c526ffed569b82e349c3). Hope it helps someone at least.
